### ISSUE TITLE
Crash on python notification problems

### ISSUE THREAD

**Issue by mordonez** [joedicastro/lftp-mirror#1]
The notification(message) method doesn't catch exceptions thrown by the pynotify module

lftp-mirror _should_ handle that gracefully and either ignore the failing/missing desktop notifications, i.e. simply try/except pass for the show() call, or try to catch them and display a dialog instead.

trace:

Traceback (most recent call last):
  File "/home/salon/lftp/src/lftp_mirror.py", line 750, in <module>
    main()
  File "/home/salon/lftp/src/lftp_mirror.py", line 738, in main
    mirror(args, log)
  File "/home/salon/lftp/src/lftp_mirror.py", line 616, in mirror
    notify('Mirroring with {0}...'.format(args.site), 'sync')
  File "/home/salon/lftp/src/lftp_mirror.py", line 541, in notify
    note.show()
gio.Error: GDBus.Error:org.freedesktop.Notifications.MaxNotificationsExceeded: Exceeded maximum number of notifications

**Comment by joedicastro** [comment]
You're right, my fault. 

Solved in e38cec1aa1 by catching and logging the exceptions
