### ISSUE TITLE
Incorrect padding

### ISSUE THREAD

**Issue by ralphte** [joedicastro/lftp-mirror#4]
When ever I try to run this script this is the error that I get.

Traceback (most recent call last):
  File "lftp_mirror.py", line 759, in <module>
    main()
  File "lftp_mirror.py", line 744, in main
    cfg.get(sect, 'options')))
  File "lftp_mirror.py", line 686, in parse_parms
    base64.b64decode(parms[5]),
  File "/usr/lib/python2.7/base64.py", line 76, in b64decode
    raise TypeError(msg)
TypeError: Incorrect padding

**Comment by ralphte** [comment]
Never mind it was in easy fix the password need to be in base64 encoding. It sayes it all the the output
